language: python
os: linux
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coverage pytest pytest-cov flake8 coveralls pyyaml
  - pip install -r REQUIREMENTS.txt
script:
  - pytest -v --cov=preflightpy --cov-report=term-missing
  - flake8 preflightpy
  - flake8 tests
after_success:
  - coveralls
